using System.IO;
using System.Linq;
using AriaEngine.Packaging;
using AriaEngine.Assets;
using Xunit;

namespace AriaEngine.Tests;

public class PakV3AssetLoadingE2ETests
{
    [Fact]
    public void V3SplitPak_GeneratedPaths_HaveCorrectPrefix()
    {
        // Verify the pak files generated by build have correct PathStrings
        // Find repo root from test assembly location
        var testDir = new FileInfo(typeof(PakV3AssetLoadingE2ETests).Assembly.Location).DirectoryName!;
        var repoRoot = Directory.GetParent(testDir)!.Parent!.Parent!.Parent!.Parent!.FullName;
        var dataArid = Path.Combine(repoRoot, "build", "data.arid");
        var scenarioAris = Path.Combine(repoRoot, "build", "scenario.aris");
        var voiceAriv = Path.Combine(repoRoot, "build", "voice.ariv");

        Assert.True(File.Exists(dataArid), $"data.arid should exist at {dataArid}");
        Assert.True(File.Exists(scenarioAris), $"scenario.aris should exist at {scenarioAris}");
        Assert.True(File.Exists(voiceAriv), $"voice.ariv should exist at {voiceAriv}");

        using var dataFs = File.OpenRead(dataArid);
        var dataReader = PakArchiveV3Reader.Read(dataFs);
        // All data entries should have assets/ prefix
        foreach (var path in dataReader.PathStrings)
        {
            Assert.StartsWith("assets/", path);
        }

        using var scenarioFs = File.OpenRead(scenarioAris);
        var scenarioReader = PakArchiveV3Reader.Read(scenarioFs);
        // Scenario entries may be compiled output under scripts/ or source scripts under assets/.
        foreach (var path in scenarioReader.PathStrings)
        {
            Assert.True(
                path.StartsWith("assets/") || path.StartsWith("scripts/"),
                $"unexpected scenario path prefix: {path}");
        }

        using var voiceFs = File.OpenRead(voiceAriv);
        var voiceReader = PakArchiveV3Reader.Read(voiceFs);
        // Voice entries should have assets/ prefix
        foreach (var path in voiceReader.PathStrings)
        {
            Assert.StartsWith("assets/", path);
        }
    }

    [Fact]
    public void V3SplitPak_ProviderCanLoadAllCategories()
    {
        var testDir = new FileInfo(typeof(PakV3AssetLoadingE2ETests).Assembly.Location).DirectoryName!;
        var repoRoot = Directory.GetParent(testDir)!.Parent!.Parent!.Parent!.Parent!.FullName;
        var paks = new[]
        {
            Path.Combine(repoRoot, "build", "scenario.aris"),
            Path.Combine(repoRoot, "build", "data.arid"),
            Path.Combine(repoRoot, "build", "voice.ariv")
        };

        if (!paks.All(File.Exists))
        {
            // Skip if paks weren't generated
            return;
        }

        using var provider = new PakAssetProviderV3(paks);

        // Scenario (no prefix)
        Assert.True(provider.Exists("scripts/main.aria"), "Should find scripts/main.aria");

        // Data (with assets/ prefix in pak, engine requests with or without)
        Assert.True(provider.Exists("assets/bg/bg_title.bmp"), "Should find assets/bg/bg_title.bmp");
        Assert.True(provider.Exists("assets/fonts/NotoSansJP-Regular.ttf"), "Should find fonts");

        // Voice (with assets/ prefix)
        Assert.True(provider.Exists("assets/sound/shutter.mp3"), "Should find shutter.mp3");
    }
}
